Ros maps
RoboticaUtnFrba/cartographer pull request #1
Opened 2020-06-19 01:58 UTC by BarceloChristian

Disable system wide protobuf install.
Makes the occupied cells darker.

2020-06-19 20:34 UTC, eborghi10 requested changes

2020-06-19 20:34 UTC, eborghi10 commented on cartographer/io/submap_painter.cc
> +    const uint8_t alpha_value =
Can you explain what this change does?

2020-06-19 22:29 UTC, BarceloChristian commented on cartographer/io/submap_painter.cc
> +    const uint8_t alpha_value =
It's based on Ojura's comment here: https://github.com/cartographer-project/cartographer/issues/1498#issuecomment-464308882

```
This way, we make darker only the cells which are actually occupied, and
not grayish-looking cells in the final map which are actually free, but just
really uncertain so they ended up looking dark after blending.
```
I'll add a comment in the code.

2020-06-23 02:27 UTC, eborghi10 requested changes

2020-06-23 02:27 UTC, eborghi10 commented on scripts/install_proto3.sh
> +  sudo ninja install
Shouldn't this be done by default?

If you want to enable it only for Travis, you can use `CI`, see [here](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables).

2020-06-24 21:45 UTC, BarceloChristian commented on scripts/install_proto3.sh
> +  sudo ninja install
By default, it will install proto system-wide.
It will install proto locally only if you run `install_proto3.sh --local`

2020-06-25 00:30 UTC, merged